baseurl = "http://zealoct.github.io/"
languageCode = "zh-cn"
title = "Zea's"
disqusShortName = "hanjc"

[[menu.main]]
	name = "Archives"
    url = "/post/"

[[menu.main]]
	name = "Notes"
    url = "/notes/"

[author]
	name = "jc han"

[indexes]
	category = "categories"
	tag = "tags"

[params]
	github = "http://github.com/zealoct"
    linkedin = ""
    googleplus = ""
    facebook = ""
    twitter = "http://twitter.com/zealoct"