baseurl = ""
languageCode = "zh-cn"
title = "Zea's"
disqusShortName = "hanjc"

[author]
	name = "jc han"

[indexes]
	category = "categories"
	tag = "tags"

[params]
	github = "http://github.com/zealoct"
    linkedin = ""
    googleplus = ""
    facebook = ""
    twitter = "http://twitter.com/zealoct"